### ISSUE TITLE
Search strings containing '+' behave oddly

### ISSUE THREAD

**Issue by bran-solo** [badLlama121/discordBot#17]
Repro steps:

1. Say 'test+poop'
2. Do a '!s +/and'

Expected:
Output of 'testandpoop'

Actual:
Bot doesn't respond

Probably something weird with how we're using regexes.

**Comment by bran-solo** [comment]
Have also seen weird stuff with strings containing question marks. Let me know if you want separate issue.

**Comment by bran-solo** [comment]
Hm seeing another one where www.google.com with '!s google/poop' outputs 'http://www.%2A%2Apoop%2A%2A.com/'.

Guessing if we want to keep using regexp in this way we need to escape the input string.

**Comment by bran-solo** [comment]
Also fucks up search queries containing '$'

**Comment by zippy1981** [comment]
literally just escapt the + like `!s love\+/hare-` and it will work. I think its funny that bejean wil use a real regex with backticks.
