### ISSUE TITLE
Implement initial version of string scoring

### ISSUE THREAD

**Issue by bran-solo** [badLlama121/discordBot#20]
Base requirements:

1. Persistent store keeps track of scores of all phrases.
2. 'string' followed by ++ increments score for that phrase.
3. 'string' followed by -- decrements score for that phrase.
4. '!score <string>' should reply with the score for that phrase.

Initial version will not have any sort of filtering / spam protection.

"One blocked message" logic should apply to queries triggering this.

Score needs to persist even when the bot goes offline and comes back online later. I'd be fine with just storing dead simple scores in a flat file but if you want to go nuts and record when/who voted for what to do more intricate stuff with stats, go nuts.

**Comment by zippy1981** [comment]
@bran-solo  I didnt implement 'one blocked message' logice here. Does it not score if 'one blocked message' happens?

**Comment by bran-solo** [comment]
As currently implemented it only applies to !s. Why don't we make it apply for all queries on the bot? (I can get off my ass and do more code changes if you'd like)

**Comment by zippy1981** [comment]
Implemented in #24
